### ISSUE TITLE
Wrong paper URL

### ISSUE THREAD

**Issue by fbaeumer** [oliverguhr/german-sentiment#2]
Thanks for the package. It is very fast and a good idea. Also thanks that code is actually delivered for a scientific paper. Unfortunately the URL to the paper seems to be wrong, both here (DOI, 404) and in the package manager (wrong paper). Maybe you want to change this, then it is easier to read the background.

**Comment by DJCordhose** [comment]
Right, seems there has been a shift by one, the correct link to the paper is here

http://www.lrec-conf.org/proceedings/lrec2020/pdf/2020.lrec-1.202.pdf

**Comment by oliverguhr** [comment]
Thanks for the feedback! I used the bibcode that LREC provided. I think the issue here is, that ACL has not listed the LREC proceedings yet and that the link will work then. Until then I keep this issue open.
