### ISSUE TITLE
Feedback regarding case

### ISSUE THREAD

**Issue by PhilipMay** [oliverguhr/german-sentiment#4]
Hi,
I just had a look on your training data and just wanted to give feedback.
You have all texts lowercased but the language model you did use was case sensitive.

See tokenizer_config.json:

```json
{"do_lower_case": false, "model_max_length": 512, "unk_token": "[UNK]", "sep_token": "[SEP]", "pad_token": "[PAD]", "cls_token": "[CLS]", "mask_token": "[MASK]"}
```

IMO this will reduce quality because "Dummkopf" `!=` "dummkopf" for the pretrained language model.

**Comment by oliverguhr** [comment]
Hi Philipp,
technically you are right - I used a cased model because there were not uncased models available back then. Using lowercased texts did yield better results than cased texts, even with the cased model.

Hope that helps,
Oliver

**Comment by PhilipMay** [comment]
Hmm - that is very strange. Maybe a reandom initialized BERT model would have been even better? ;-)
