### ISSUE TITLE
Small error that breaks example code on Hugging Face model card

### ISSUE THREAD

**Issue by rnckp** [oliverguhr/german-sentiment#7]
Hi Oliver

First of all – thanks very much for making your model available. Really helpful and very much appreciated.

I noticed a small quirk that broke [your sample code on Hugging Face](https://huggingface.co/oliverguhr/german-sentiment-bert) for me:

![Bildschirmfoto 2021-11-17 um 20 31 31](https://user-images.githubusercontent.com/85753179/142270008-c6b8baed-5c16-480d-8c58-78694c2a5bf3.png)

In the function `clean_text` you start by replacing `\n` with spaces. If I just copy and paste the code I don't copy the invisible `\n` but get an actual line break in my IDE (Sublime). This leads to wrong predictions. 

If I replace the line break with an actual `\n` I get correct predictions. It might be helpful to fix that in the sample code if possible.

Again – thanks for your work. 👍

Have a great day!

**Comment by oliverguhr** [comment]
Hi Patrick,
thanks for the feedback and thanks for pointing this out. I literally copied the code from the sentiment python package, which does use "\n"

https://github.com/oliverguhr/german-sentiment-lib/blob/master/germansentiment/sentimentmodel.py#L44

However, I fixed the model card. Thanks again!
