### ISSUE TITLE
FastText model not found

### ISSUE THREAD

**Issue by Stamenov** [oliverguhr/german-sentiment#8]
Hi,

According to your paper, you have compared the BERT model to a FastText model, the latter of which I would like to download and test.
Would you be willing to update the link with the FastText model?

I suppose https://www2.htw-dresden.de/~guhr/dist/sentiment/models.zip needs to be updated.

Thanks in advance,
Best

**Comment by oliverguhr** [comment]
Hi, 
yes the link is outdated, the new one is in the readme:

https://zenodo.org/record/3693810/files/models.zip?download=1


Where did you find the old link?

Best,
Oli

**Comment by Stamenov** [comment]
Hi, thanks a lot.
Found it here:
https://github.com/oliverguhr/german-sentiment/blob/master/download-models-and-data.sh#L2
