### ISSUE TITLE
Question: Text cleaning for BERT and FastText

### ISSUE THREAD

**Issue by Stamenov** [oliverguhr/german-sentiment#9]
Hi there,

I have a question connected to the way the data was cleaned for both models.
I guess before training for the FastText model, all these cleaners have been used: https://github.com/oliverguhr/german-sentiment/blob/master/fasttext/textcleaner.py#L66

This is why for example the FastText model doesnt "understand" emojis, while the BERT model does: 
https://huggingface.co/oliverguhr/german-sentiment-bert?text=%F0%9F%98%A1

In the BERT folder, I dont see similar cleaners, but at the same time, the minimal example in huggingface hub https://huggingface.co/oliverguhr/german-sentiment-bert?#a-minimal-working-sample  show a subset of the FastText cleaners/preprocessors.

Could you please clarify which cleaners are recommended/have been used for the preprocessing of the BERT train data?

**Comment by oliverguhr** [comment]
Hi @Stamenov,
[this code](https://github.com/oliverguhr/german-sentiment/blob/master/fasttext/textcleaner.py#L66) from the FastText folder has been used for both models. The preprocessing pipeline creates a file with the preprocessed samples that is then used to train the fasttext / bert model. 

Emojis and smileys are not removed from the text, but replaced with a word. Take a look at these files: 
https://github.com/oliverguhr/german-sentiment/blob/master/source-data/scare_v1.0.0_data/dictionaries/emoticons.txt
https://github.com/oliverguhr/german-sentiment/blob/master/source-data/scare_v1.0.0_data/dictionaries/smiley.txt

I did not put this preprocessing step into the minimal working example, as this would require external files and add extra complexity. 

So if you need to handle emojis and smileys, you should add this preprocessing step for your data.

**Comment by Stamenov** [comment]
Hi @oliverguhr,
Thanks for the quick response as always.

I am then wondering how the BERT model understands emojies if you have replaced them?
See: https://huggingface.co/oliverguhr/german-sentiment-bert?text=%F0%9F%98%A1

You also dont really specify which pre-trained BERT you have used.
Is it deepset's german bert https://huggingface.co/bert-base-german-cased ?

**Comment by oliverguhr** [comment]
Yes I used deepsets german model, back then it was the only German model available. 

Regarding the emojis I can only guess. But I think the model was trained on texts containing emojis and now it can relate words appearing in emotional contexts to emojis that are used in these contexts.
